"""兼容导入；Interaction DTO 已迁至 assistant_agent.contracts。"""

from assistant_agent.contracts.interactions import (
    ApprovalChoice,
    ApprovalDecision,
    ApprovalRequest,
    BudgetResource,
    ContinueDecision,
    ContinueRequest,
    DefinitionChangeDecision,
    DefinitionChangeRequest,
    DefinitionDifferenceInfo,
    InteractionDecision,
    InteractionRequest,
    InteractionRequestBase,
    QuestionAnswer,
    QuestionRequest,
    RecoveryChoice,
    RecoveryDecision,
    RecoveryRequest,
    ScopeInfo,
    new_request_id,
)

__all__ = [
    "ApprovalChoice",
    "ApprovalDecision",
    "ApprovalRequest",
    "BudgetResource",
    "ContinueDecision",
    "ContinueRequest",
    "DefinitionChangeDecision",
    "DefinitionChangeRequest",
    "DefinitionDifferenceInfo",
    "InteractionDecision",
    "InteractionRequest",
    "InteractionRequestBase",
    "QuestionAnswer",
    "QuestionRequest",
    "RecoveryChoice",
    "RecoveryDecision",
    "RecoveryRequest",
    "ScopeInfo",
    "new_request_id",
]
